package com.vydya.theschool.web.constants;

import com.vydya.theschool.common.constants.TSConstants;

/**
*  This file contains constants using in web layer
*/
public interface WebConstants {
	

	public final static String SESSION_USER_NAME = "user_name";
	public final static String SESSION_USER_DISPLAY_NAME = "user_display_name";
	public final static String SESSION_USER_LOCALE = "user_locale";
	public final static String SESSION_USER_ROLE_PERMISSIONS = "user_role_permissions";
	public final static String SESSION_USER_LAST_LOGIN = "user_last_login";
	public static final String SESSION_USER_GROUP_ID = "user_group_id";
	public static final String SESSION_USER_ROLE_ID = "user_role_id";
	public static final String SESSION_USER_TYPE = "user_type";
	public static final String SESSION_ADMIN_ROLE_ID = "admin_role_id";
	public final static String SESSION_USER_ROLE_TYPE = "user_role_type";
	public final static String SESSION_CAPTCHA_TEXT = "captcha_text";
	public final static String SESSION_SUCCESS_MESSAGE = "success_key";
	public final static String SESSION_ALERT_MESSAGE = "alert_key";
	public final static String SESSION_BUILD_VERSION = "build_version";
	public final static String SESSION_USER_MERCHANT_ID = "user_merchant_id";
	public final static String SESSION_USER_MERCHANT_ID_CHECKED = "merchantIdChecked";	
	public final static String EDIT_PROPERTY_MULTIPLE = "multiple";
	public final static String EDIT_PROPERTY_INDIVIDUAL = "individual";
	
	
	public final static String HOME_REPORT_PAGE = "home_reportpage";
	
	public final static String ACTION_LOGIN = "login";
	public final static String ACTION_CHANGEPASSWORD = "login";
	public final static String REPORT_LOGIN = "login";

	public final static String SUFFIX_DOT_DO = ".do";
	public final static String SUFFIX_DOT_HTM = ".htm";
	public final static String SEPARATOR_SLASH = "/";
	public final static String SEPARATOR_DOT = ".";
	public final static String SEPARATOR_COLON = ":";
	public final static  int DEFAULT_BUFFER_SIZE = 1048576;
	
	public final static String CATEGORY = "Category";
	
	public final static String ADD = "add";
	public final static String ADD_OR_EDIT = "addOrEdit";
	public final static String SAVE = "save";
	public final static String IMAGE = "Image";
	public final static String BOOK = "Book";
	public final static String BOOKS = "books";
	
	public final static String VIDEO = "Video";
	public final static String TOPPER = "Topper";
	public final static String TOPPERS = "Toppers";
	public final static String GROUP = "Group";
	public final static String IMAGES = "Images";
	public final static String DELETE = "delete";
	public final static String VIEW = "view";
	public final static String VIEW_ALL = "viewAll";
	public final static String UPDATE = "update";
	public final static String EDIT = "edit";
	public final static String CROP = "crop";
	public final static String LOADALL = "loadAll";
	public final static String LOAD_UPDATED = "loadUpdated";
	public final static String SEARCH = "search";
	
	public final static String CLASSES = "classes";
	

	
	public final static String REDIRECT = "redirect";
	public final static String FORWARD = "forward";
	public static final String REDIRECT_VIEWALL = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	
	
	public final static String LOGIN_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_LOGIN+SEPARATOR_SLASH+TSConstants.ACTION_LOGIN+SUFFIX_DOT_HTM;
	//public final static String LOGIN_ACTION = SEPARATOR_SLASH+TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_LOGIN+SEPARATOR_SLASH+TSConstants.ACTION_LOGIN+SUFFIX_DOT_HTM;
	
	//public final static String VIEW_PAYEE_SETTLEMENT_REPORT_DEFAULT_ACTION = TSConstants.MANAGE_PAYEE_SETTLEMENT_REPORT+SEPARATOR_SLASH+TSConstants.VIEW_PAYEE_SETTLEMENT_ACTION+SUFFIX_DOT_DO;
	
	public static final String VIEW_ALL_HOMEPAGE_IMAGES =  TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_HOMEPAGE+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String ADD_HOMEPAGE_IMAGES = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_HOMEPAGE+SEPARATOR_SLASH+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	public static final String EDIT_HOMEPAGE_IMAGES = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_HOMEPAGE+SEPARATOR_SLASH+TSConstants.ACTION_EDIT+SUFFIX_DOT_HTM;
	public static final String REDIRECT_VIEWALL_HOMEPAGE_IMAGES = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String DELETE_HOMEPAGE_IMAGES = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_HOMEPAGE+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+SUFFIX_DOT_HTM;
	public static final String ADD_EDIT_HOMEPAGEIMAGE = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_HOMEPAGE+SEPARATOR_SLASH+TSConstants.ACTION_ADD_OR_EDIT+SUFFIX_DOT_HTM;
	public static final String UPLOAD_HOMEPAGEIMAGE = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_HOMEPAGE+SEPARATOR_SLASH+TSConstants.ACTION_UPLOAD_IMAGE+SUFFIX_DOT_HTM;
	
	//views 
	public static final String VIEWNAME_HOMEPAGEIMAGES_ALL = TSConstants.MANAGE_HOMEPAGE+SEPARATOR_DOT+VIEW_ALL;
	public static final String VIEWNAME_HOMEPAGEIMAGES_ADD_OR_EDIT = TSConstants.MANAGE_HOMEPAGE+SEPARATOR_DOT+ADD_OR_EDIT;
	
	public static final String VIEW_EVENT_IMAGES = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_EVENTS+SEPARATOR_SLASH+TSConstants.ACTION_VIEW_EVENT_IMAGES+SUFFIX_DOT_HTM;
	public static final String ADD_EVENT_IMAGES = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_EVENTS+SEPARATOR_SLASH+TSConstants.ACTION_ADD_EVENT_IMAGES+SUFFIX_DOT_HTM;
	public static final String REDIRECT_VIEW_EVENT_IMAGES = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_VIEW_EVENT_IMAGES+SUFFIX_DOT_HTM;
	public static final String REDIRECT_ADD_EVENT_IMAGES = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_ADD_EVENT_IMAGES+SUFFIX_DOT_HTM;
	public static final String DELETE_EVENT_IMAGES = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_EVENTS+SEPARATOR_SLASH+TSConstants.ACTION_DELETE_EVENT_IMAGES+SUFFIX_DOT_HTM;
	
	public static final String VIEWNAME_EVENTS_ALL = TSConstants.MANAGE_EVENTS+SEPARATOR_DOT+VIEW_ALL;
	public static final String VIEWNAME_EVENT_ADD_OR_EDIT = TSConstants.MANAGE_EVENTS+SEPARATOR_DOT+ADD_OR_EDIT;
	
	
	public static final String VIEW_EVENTS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_EVENTS+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String VIEW_EVENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_EVENTS+SEPARATOR_SLASH+TSConstants.ACTION_VIEW+SUFFIX_DOT_HTM;
	
	public static final String ADD_EVENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_EVENTS+SEPARATOR_SLASH+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	public static final String REDIRECT_VIEW_EVENT = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String DELETE_EVENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_EVENTS+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+SUFFIX_DOT_HTM;
	public static final String REDIRECT_ADD_EVENT = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	public static final String EDIT_EVENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_EVENTS+SEPARATOR_SLASH+TSConstants.ACTION_EDIT+SUFFIX_DOT_HTM;
	public static final String UPLOAD_EVENTIMAGE = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_EVENTS+SEPARATOR_SLASH+TSConstants.ACTION_UPLOAD_IMAGE+SUFFIX_DOT_HTM;
	public static final String LOAD_EVENTS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_EVENTS+SEPARATOR_SLASH+TSConstants.ACTION_LOAD+SUFFIX_DOT_HTM;
	
	public static final String VIEW_CLIENTS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CLIENTS+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String DELETE_CLIENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CLIENTS+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+SUFFIX_DOT_HTM;
	
	//Column Menu contents
	public static final String VIEW_ALL_COLUMNCONTENTS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_COLUMNCONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String VIEW_COLUMNCONTENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_COLUMNCONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_VIEW+SUFFIX_DOT_HTM;
	public static final String ADD_COLUMNCONTENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_COLUMNCONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	public static final String DELETE_COLUMNCONTENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_COLUMNCONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+SUFFIX_DOT_HTM;
	public static final String REDIRECT_COLUMNCONTENTS = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String UPDATE_COLUMNCONTENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_COLUMNCONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_UPDATE+SUFFIX_DOT_HTM;
	public static final String EDIT_COLUMNCONTENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_COLUMNCONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_EDIT+SUFFIX_DOT_HTM;
	public static final String GET_COLUMNCONTENTS_LIST = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_COLUMNCONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_GET_CCLIST+SUFFIX_DOT_HTM;
	public final static String REORDER_COLUMNCONTENTS_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_COLUMNCONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_REORDER+SUFFIX_DOT_HTM;
	public final static String RELOAD_COLUMNCONTENTS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_COLUMNCONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_RELOAD+SUFFIX_DOT_HTM;
	
	
	public static final String VIEWNAME_COLUMNCONTENTS_ADD = TSConstants.MANAGE_COLUMNCONTENTS+SEPARATOR_DOT+ADD;
	public static final String VIEWNAME_COLUMNCONTENTS_SAVE = TSConstants.MANAGE_COLUMNCONTENTS+SEPARATOR_DOT+SAVE;
	public static final String VIEWNAME_COLUMNCONTENTS_VIEW = TSConstants.MANAGE_COLUMNCONTENTS+SEPARATOR_DOT+VIEW;
	public static final String VIEWNAME_COLUMNCONTENTS_ALL = TSConstants.MANAGE_COLUMNCONTENTS+SEPARATOR_DOT+VIEW_ALL;
	
	
	//Notifications
	public static final String VIEW_ALL_NOTIFICATIONS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_NOTIFICATIONS+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String VIEW_NOTIFICATION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_NOTIFICATIONS+SEPARATOR_SLASH+TSConstants.ACTION_VIEW+SUFFIX_DOT_HTM;
	public static final String ADD_NOTIFICATION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_NOTIFICATIONS+SEPARATOR_SLASH+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	public static final String DELETE_NOTIFICATION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_NOTIFICATIONS+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+SUFFIX_DOT_HTM;
	public static final String REDIRECT_NOTIFICATION = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String UPDATE_NOTIFICATION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_NOTIFICATIONS+SEPARATOR_SLASH+TSConstants.ACTION_UPDATE+SUFFIX_DOT_HTM;
	public static final String EDIT_NOTIFICATION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_NOTIFICATIONS+SEPARATOR_SLASH+TSConstants.ACTION_EDIT+SUFFIX_DOT_HTM;
	
	public static final String VIEWNAME_NOTIFICATIONS_ADD = TSConstants.MANAGE_NOTIFICATIONS+SEPARATOR_DOT+ADD;
	public static final String VIEWNAME_NOTIFICATIONS_SAVE = TSConstants.MANAGE_NOTIFICATIONS+SEPARATOR_DOT+SAVE;
	public static final String VIEWNAME_NOTIFICATIONS_VIEW = TSConstants.MANAGE_NOTIFICATIONS+SEPARATOR_DOT+VIEW;
	public static final String VIEWNAME_NOTIFICATIONS_ALL = TSConstants.MANAGE_NOTIFICATIONS+SEPARATOR_DOT+VIEW_ALL;
	
	
	//Contents
	public static final String VIEW_ALL_CONTENTS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String VIEW_CONTENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_VIEW+SUFFIX_DOT_HTM;
	public static final String ADD_CONTENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	public static final String DELETE_CONTENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+SUFFIX_DOT_HTM;
	public static final String REDIRECT_CONTENT = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String UPDATE_CONTENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_UPDATE+SUFFIX_DOT_HTM;
	public static final String EDIT_CONTENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_EDIT+SUFFIX_DOT_HTM;
	public static final String VIEW_ALL_ATTACHMENTS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_ATTACHMENTS+SUFFIX_DOT_HTM;
	public static final String DELETE_ATTACHMENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_DELETE_ATTACHMENT+SUFFIX_DOT_HTM;
	
	//Menus
	public static final String VIEW_ALL_MENUS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_MENU+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String VIEW_MENU = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_MENU+SEPARATOR_SLASH+TSConstants.ACTION_VIEW+SUFFIX_DOT_HTM;
	public static final String ADD_MENU = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_MENU+SEPARATOR_SLASH+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	public static final String DELETE_MENU = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_MENU+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+SUFFIX_DOT_HTM;
	public static final String REDIRECT_MENU = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String UPDATE_MENU = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_MENU+SEPARATOR_SLASH+TSConstants.ACTION_EDIT+SUFFIX_DOT_HTM;
	public static final String UPLOAD_MENU_IMAGE = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_MENU+SEPARATOR_SLASH+TSConstants.ACTION_UPLOAD_IMAGE+SUFFIX_DOT_HTM;
	public static final String LOAD_MENU = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_MENU+SEPARATOR_SLASH+TSConstants.ACTION_LOAD+SUFFIX_DOT_HTM;
	public static final String VIEW_MENU_ATTACHMENTS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_MENU+SEPARATOR_SLASH+TSConstants.ACTION_ATTACHMENTS+SUFFIX_DOT_HTM;
	public static final String DELETE_MENU_ATTACHMENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_MENU+SEPARATOR_SLASH+TSConstants.ACTION_DELETE_ATTACHMENT+SUFFIX_DOT_HTM;
	
	
	
	public static final String VIEW_CONTENT_CAT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_VIEW+CATEGORY+SUFFIX_DOT_HTM;
	public static final String ADD_CONTENT_CAT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_ADD+CATEGORY+SUFFIX_DOT_HTM;
	public static final String DELETE_CONTENT_CAT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+CATEGORY+SUFFIX_DOT_HTM;
	public static final String REDIRECT_CONTENT_CAT = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String UPDATE_CONTENT_CAT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_UPDATE+CATEGORY+SUFFIX_DOT_HTM;
	public static final String EDIT_CONTENT_CAT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CONTENTS+SEPARATOR_SLASH+TSConstants.ACTION_EDIT+CATEGORY+SUFFIX_DOT_HTM;
	
	public static final String VIEWNAME_CONTENT_ADD = TSConstants.MANAGE_CONTENTS+SEPARATOR_DOT+ADD;
	public static final String VIEWNAME_CONTENT_SAVE = TSConstants.MANAGE_CONTENTS+SEPARATOR_DOT+SAVE;
	public static final String VIEWNAME_CONTENT_VIEW = TSConstants.MANAGE_CONTENTS+SEPARATOR_DOT+VIEW;
	public static final String VIEWNAME_CONTENTS_ALL = TSConstants.MANAGE_CONTENTS+SEPARATOR_DOT+VIEW_ALL;
	public static final String VIEWNAME_ATTACHMENTS = TSConstants.MANAGE_CONTENTS+SEPARATOR_DOT+TSConstants.ACTION_ATTACHMENTS;
	public static final String VIEWNAME_ATTACH = TSConstants.MANAGE_CONTENTS+SEPARATOR_DOT+TSConstants.ACTION_ATTACH;
	public static final String VIEWNAME_CONTENT_ADD_OR_EDIT = TSConstants.MANAGE_CONTENTS+SEPARATOR_DOT+ADD_OR_EDIT;
	
	public static final String VIEWNAME_CONTENT_CAT_ADD_OR_EDIT = TSConstants.MANAGE_CONTENTS+SEPARATOR_DOT+ADD_OR_EDIT+CATEGORY;
	
	public static final String VIEWNAME_VIEW_BOOKS = TSConstants.MANAGE_LIBRARY+SEPARATOR_DOT+TSConstants.ACTION_BOOKS;
	//MENU views
	public static final String VIEWNAME_MENU_ADD = TSConstants.MANAGE_MENU+SEPARATOR_DOT+ADD;
	public static final String VIEWNAME_MENU_SAVE = TSConstants.MANAGE_MENU+SEPARATOR_DOT+SAVE;
	public static final String VIEWNAME_MENU_VIEW = TSConstants.MANAGE_MENU+SEPARATOR_DOT+VIEW;
	public static final String VIEWNAME_MENU_ALL = TSConstants.MANAGE_MENU+SEPARATOR_DOT+VIEW_ALL;
	public static final String VIEWNAME_MENU_ADD_OR_EDIT = TSConstants.MANAGE_MENU+SEPARATOR_DOT+ADD_OR_EDIT;
	
	//SCHOOL PAGES
	public static final String VIEWNAME_SCHOOL_HOME = "school.home";
	public static final String VIEWNAME_SCHOOL_ABOUTUS = "school.aboutus";
	public static final String VIEWNAME_SCHOOL_CONTACTUS = "school.contactus";
	public static final String VIEWNAME_SCHOOL_ADMISSIONS = "school.admissions";
	public static final String VIEWNAME_SCHOOL_ADMINISTRATION = "school.admin";
	public static final String VIEWNAME_SCHOOL_EXAMINATION = "school.examination";
	public static final String VIEWNAME_SCHOOL_ACADEMICS = "school.academics";
	public static final String VIEWNAME_SCHOOL_FECILITIES = "school.fecilities";
	public static final String VIEWNAME_SCHOOL_ACHIEVEMENTS = "school.achievements";
	public static final String VIEWNAME_SCHOOL_RANKS = "school.ranks";
	public static final String VIEWNAME_SCHOOL_INFRASTRUCTURE = "school.infrastructure";
	public static final String VIEWNAME_SCHOOL_EVENTS = "school.events";
	public static final String VIEWNAME_SCHOOL_EVENT = "school.event";
	public static final String VIEWNAME_EVENT_IMAGES = "school.event.images";
	public static final String VIEWNAME_ERROR = "school.error";
	
	public static final String VIEWNAME_GALLERY = "school.gallery";
	public static final String VIEWNAME_GALLERY_IMAGES = "school.gallery.images";
	
	public static final String VIEWNAME_TOPPERS = "school.toppers";
	public static final String VIEWNAME_TOPPERS_STUDENTS = "school.toppers.students";
	
	public static final String VIEWNAME_NOTIFICATIONS = "school.notifications";
	public static final String VIEWNAME_NOTIFICATION = "school.notification";
	public static final String VIEWNAME_BOOKS = "library.books";
	public static final String VIEWNAME_LIBRARY = "library.library";
	
	public static final String VIEW_NAME_VIEW_EVENTS = TSConstants.MANAGE_EVENTS+SEPARATOR_DOT+TSConstants.ACTION_VIEWALL;
	public static final String VIEW_NAME_VIEW_EVENT = TSConstants.MANAGE_EVENTS+SEPARATOR_DOT+TSConstants.ACTION_VIEW;

	public static final String VIEW_NAME_VIEW_CLIENTS = TSConstants.MANAGE_CLIENTS+SEPARATOR_DOT+TSConstants.ACTION_VIEWALL;
	
	
	//Student
	public static final String SEARCH_VIEW_STUDENTS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_STUDENTS+SEPARATOR_SLASH+TSConstants.ACTION_SEARCH+SUFFIX_DOT_HTM;
	public static final String ADD_STUDENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_STUDENTS+SEPARATOR_SLASH+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	public static final String VIEW_STUDENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_STUDENTS+SEPARATOR_SLASH+TSConstants.ACTION_VIEW+SUFFIX_DOT_HTM;
	public static final String UPDATE_STUDENT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_STUDENTS+SEPARATOR_SLASH+TSConstants.ACTION_UPDATE+SUFFIX_DOT_HTM;
	public static final String LOAD_UPDATED_STUDENTS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_STUDENTS+SEPARATOR_SLASH+TSConstants.ACTION_LOAD_UPDATED+SUFFIX_DOT_HTM;
	public static final String UPLOAD_STUDENT_PHOTO = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_STUDENTS+SEPARATOR_SLASH+TSConstants.ACTION_UPLOAD_IMAGE+SUFFIX_DOT_HTM;
	public static final String UPDATE_STUDENT_MARKS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_STUDENTS+SEPARATOR_SLASH+TSConstants.ACTION_UPDATE_STUDENTMARKS+SUFFIX_DOT_HTM;
	public static final String VIEW_ALL_STUDENTS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_STUDENTS+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	
	
	//Student Marks
	public static final String SEARCH_VIEW_EXPORT_STUDENT_MARKS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_STUDENT_MARKS+SEPARATOR_SLASH+TSConstants.ACTION_EXPORT+SUFFIX_DOT_HTM;
	public static final String SEARCH_VIEW_STUDENT_MARKS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_STUDENT_MARKS+SEPARATOR_SLASH+TSConstants.ACTION_SEARCH+SUFFIX_DOT_HTM;
	public static final String UPDATE_MARKS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_STUDENT_MARKS+SEPARATOR_SLASH+TSConstants.ACTION_UPDATE+SUFFIX_DOT_HTM;
	public static final String VIEW_ALL_MARKS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_STUDENT_MARKS+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	
	//Gallery
	
	
	//public static final String ADD_EDIT_GALLERY = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_ADD_OR_EDIT+SUFFIX_DOT_HTM;
	//public static final String ADD_EDIT_GALLERYIMAGE = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_ADD_OR_EDIT+IMAGE+SUFFIX_DOT_HTM;
	public static final String LOAD_UPDATED_GALLERYIMAGE= TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_LOAD_GALLERYIMAGES+SUFFIX_DOT_HTM;
	public static final String LOAD_UPDATED_GALLERY= TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_LOAD_GALLERY+SUFFIX_DOT_HTM;
	public static final String VIEW_GALLERY = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String ADD_GALLERY = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	public static final String EDIT_GALLERY = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_EDIT+SUFFIX_DOT_HTM;
	public static final String DELETE_GALLERY = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+SUFFIX_DOT_HTM;
	public static final String DELETE_GALLERY_IMAGE = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+IMAGE+SUFFIX_DOT_HTM;
	public static final String UPLOAD_GALLERYIMAGE = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_UPLOAD_IMAGE+SUFFIX_DOT_HTM;
	
	public static final String VIEW_GALLERY_IMAGES = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+IMAGES+SUFFIX_DOT_HTM;
	public static final String ADD_GALLERY_IMAGE = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_ADD+IMAGE+SUFFIX_DOT_HTM;
	public static final String EDIT_GALLERY_IMAGE = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_EDIT+IMAGE+SUFFIX_DOT_HTM;
	public static final String REDIRECT_ADD_GALLERY = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	public static final String REDIRECT_VIEW_ALL = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	
	
	public static final String LOAD_UPDATED_BOOK= TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_LIBRARY+SEPARATOR_SLASH+TSConstants.ACTION_LOAD_GALLERYIMAGES+SUFFIX_DOT_HTM;
	public static final String VIEW_LIBRARY = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_LIBRARY+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String ADD_LIBRARY = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_LIBRARY+SEPARATOR_SLASH+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	public static final String EDIT_LIBRARY = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_LIBRARY+SEPARATOR_SLASH+TSConstants.ACTION_EDIT+SUFFIX_DOT_HTM;
	public static final String DELETE_LIBRARY = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_LIBRARY+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+SUFFIX_DOT_HTM;
	public static final String DELETE_BOOK = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_LIBRARY+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+BOOK+SUFFIX_DOT_HTM;
	public static final String UPLOAD_BOOKIMAGE = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_LIBRARY+SEPARATOR_SLASH+TSConstants.ACTION_UPLOAD_IMAGE+SUFFIX_DOT_HTM;
	public static final String UPLOAD_LIBRARYIMAGE = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_LIBRARY+SEPARATOR_SLASH+TSConstants.ACTION_UPLOAD_IMAGE+SUFFIX_DOT_HTM;
	
	public static final String VIEW_BOOKS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_LIBRARY+SEPARATOR_SLASH+TSConstants.ACTION_BOOKS+SUFFIX_DOT_HTM;
	public static final String ADD_BOOK = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_LIBRARY+SEPARATOR_SLASH+TSConstants.ACTION_ADD+BOOK+SUFFIX_DOT_HTM;
	public static final String EDIT_BOOK = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_LIBRARY+SEPARATOR_SLASH+TSConstants.ACTION_EDIT+IMAGE+SUFFIX_DOT_HTM;
	public static final String REDIRECT_ADD_LIBRARY = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	
	
	public static final String VIEW_NAME_VIEW_LIBRARY = TSConstants.MANAGE_LIBRARY+SEPARATOR_DOT+TSConstants.ACTION_VIEWALL;
	public static final String VIEWNAME_LIBRARY_EDIT = TSConstants.MANAGE_LIBRARY+SEPARATOR_DOT+ADD_OR_EDIT;
	public static final String VIEW_NAME_VIEW_BOOKS = TSConstants.MANAGE_LIBRARY+SEPARATOR_DOT+VIEW;
	
	/*public static final String VIEW_ALL_BOOKS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_LIBRARY+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String DELETE_BOOK_CAT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_LIBRARY+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+SUFFIX_DOT_HTM;
	public static final String EDIT_BOOK_CAT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_LIBRARY+SEPARATOR_SLASH+TSConstants.ACTION_UPDATE_BOOK+SUFFIX_DOT_HTM;
	*/
	
	
	public static final String ADD_GALLERY_VIDEO = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_ADD+VIDEO+SUFFIX_DOT_HTM;
	public static final String DELETE_GALLERY_VIDEO = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+VIDEO+SUFFIX_DOT_HTM;
	public static final String EDIT_GALLERY_VIDEO = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_GALLERY+SEPARATOR_SLASH+TSConstants.ACTION_EDIT+VIDEO+SUFFIX_DOT_HTM;

	
	
	public static final String VIEWNAME_GALLERYIMAGES_ALL = TSConstants.MANAGE_GALLERY+SEPARATOR_DOT+VIEW_ALL+IMAGES;
	public static final String VIEWNAME_GALLERYIMAGES_ADD_OR_EDIT = TSConstants.MANAGE_GALLERY+SEPARATOR_DOT+ADD_OR_EDIT+IMAGE;
	public static final String VIEWNAME_GALLERY_ALL = TSConstants.MANAGE_GALLERY+SEPARATOR_DOT+VIEW_ALL;
	public static final String VIEWNAME_GALLERY_ADD_OR_EDIT = TSConstants.MANAGE_GALLERY+SEPARATOR_DOT+ADD_OR_EDIT;
	
	public static final String VIEW_NAME_VIEW_GALLERY_IMAGES = TSConstants.MANAGE_GALLERY+SEPARATOR_DOT+TSConstants.ACTION_VIEW_GALLERY_IMAGES;
	public static final String VIEW_NAME_VIEW_GALLERY = TSConstants.MANAGE_GALLERY+SEPARATOR_DOT+TSConstants.ACTION_VIEWALL;
	public static final String VIEW_NAME_ADD_GALLERY_IMAGE = TSConstants.MANAGE_GALLERY+SEPARATOR_DOT+TSConstants.ACTION_ADD+IMAGE;
	public static final String VIEW_NAME_ADD_GALLERY = TSConstants.MANAGE_GALLERY+SEPARATOR_DOT+TSConstants.ACTION_ADD;
	public static final String VIEWNAME_IMAGE_ADD_OR_EDIT = TSConstants.MANAGE_GALLERY+SEPARATOR_DOT+ADD_OR_EDIT+IMAGE;
	
	
	
// Toppers 
	
	public static final String VIEW_TOPPERS_GROUP = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_TOPPERS+SEPARATOR_SLASH+TSConstants.ACTION_VIEW_GROUPS+SUFFIX_DOT_HTM;
	public static final String ADD_TOPPERS_GROUP = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_TOPPERS+SEPARATOR_SLASH+TSConstants.ACTION_ADD_GROUP+SUFFIX_DOT_HTM;
	public static final String EDIT_TOPPERS_GROUP = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_TOPPERS+SEPARATOR_SLASH+TSConstants.ACTION_EDIT_GROUP+SUFFIX_DOT_HTM;
	public static final String DELETE_TOPPERS_GROUP = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_TOPPERS+SEPARATOR_SLASH+TSConstants.ACTION_DELETE_GROUP+SUFFIX_DOT_HTM;
	
	public static final String VIEW_TOPPERS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_TOPPERS+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String ADD_TOPPER = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_TOPPERS+SEPARATOR_SLASH+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	public static final String DELETE_TOPPER = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_TOPPERS+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+SUFFIX_DOT_HTM;
	public static final String EDIT_TOPPERS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_TOPPERS+SEPARATOR_SLASH+TSConstants.ACTION_UPDATE+SUFFIX_DOT_HTM;
	public static final String UPLOAD_TOPPERIMAGE = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_TOPPERS+SEPARATOR_SLASH+TSConstants.ACTION_UPLOAD_IMAGE+SUFFIX_DOT_HTM;
	public static final String UPLOAD_GROUPIMAGE = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_TOPPERS+SEPARATOR_SLASH+TSConstants.ACTION_UPLOAD_IMAGE+SUFFIX_DOT_HTM;
	
	public static final String VIEW_CLASSES = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CLASSES+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public static final String ADD_CLASS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CLASSES+SEPARATOR_SLASH+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	public static final String DELETE_CLASS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CLASSES+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+SUFFIX_DOT_HTM;
	public static final String EDIT_CLASS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CLASSES+SEPARATOR_SLASH+TSConstants.ACTION_UPDATE+SUFFIX_DOT_HTM;
	
	public static final String VIEW_SUBJECTS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CLASSES+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL_SUBJECTS+SUFFIX_DOT_HTM;
	public static final String ADD_SUBJECT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CLASSES+SEPARATOR_SLASH+TSConstants.ACTION_ADD_SUBJECT+SUFFIX_DOT_HTM;
	public static final String DELETE_SUBJECT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CLASSES+SEPARATOR_SLASH+TSConstants.ACTION_DELETE_SUBJECT+SUFFIX_DOT_HTM;
	public static final String EDIT_SUBJECT = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CLASSES+SEPARATOR_SLASH+TSConstants.ACTION_EDIT_SUBJECT+SUFFIX_DOT_HTM;
	
	public static final String VIEW_ATTENDANCE = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CLASSES+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL_ATTENDANCE+SUFFIX_DOT_HTM;
	
	public static final String VIEW_TEACHERS = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CLASSES+SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL_TEACHERS+SUFFIX_DOT_HTM;
	public static final String ADD_TEACHER = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CLASSES+SEPARATOR_SLASH+TSConstants.ACTION_ADD_TEACHER+SUFFIX_DOT_HTM;
	public static final String DELETE_TEACHER = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CLASSES+SEPARATOR_SLASH+TSConstants.ACTION_DELETE_TEACHER+SUFFIX_DOT_HTM;
	public static final String EDIT_TEACHER = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.MANAGE_CLASSES+SEPARATOR_SLASH+TSConstants.ACTION_EDIT_TEACHER+SUFFIX_DOT_HTM;
	
	
	public static final String VIEWNAME_TOPPERS_GROUP_ALL = TSConstants.MANAGE_TOPPERS+SEPARATOR_DOT+TSConstants.ACTION_VIEW_GROUPS;
	public static final String VIEWNAME_TOPPERS_GROUP_ADD_OR_EDIT = TSConstants.MANAGE_TOPPERS+SEPARATOR_DOT+ADD_OR_EDIT;
	
	public static final String VIEW_NAME_VIEW_TOPPERS = TSConstants.MANAGE_TOPPERS+SEPARATOR_DOT+TSConstants.ACTION_VIEWALL;
	public static final String VIEWNAME_ADD_OR_EDIT_TOPPER = TSConstants.MANAGE_TOPPERS+SEPARATOR_DOT+ADD_OR_EDIT+TOPPER;
	
	public static final String VIEWNAME_STUDENT_SEARCH = TSConstants.MANAGE_STUDENTS+SEPARATOR_DOT+SEARCH;
	public static final String VIEWNAME_STUDENT_ADD_OR_EDIT = TSConstants.MANAGE_STUDENTS+SEPARATOR_DOT+ADD_OR_EDIT;
	public static final String VIEWNAME_STUDENT_SAVE = TSConstants.MANAGE_STUDENTS+SEPARATOR_DOT+SAVE;
	public static final String VIEWNAME_STUDENT_VIEW = TSConstants.MANAGE_STUDENTS+SEPARATOR_DOT+VIEW;
	public static final String VIEWNAME_STUDENT_VIEWALL = TSConstants.MANAGE_STUDENTS+SEPARATOR_DOT+VIEW_ALL;
	
	public static final String VIEWNAME_CLASSES = TSConstants.MANAGE_CLASSES+SEPARATOR_DOT+VIEW_ALL;
	public static final String VIEWNAME_CLASS_ADD_OR_EDIT = TSConstants.MANAGE_CLASSES+SEPARATOR_DOT+ADD_OR_EDIT;
	
	public static final String VIEWNAME_SUBJECTS = TSConstants.MANAGE_CLASSES+SEPARATOR_DOT+"subjects";
	public static final String VIEWNAME_SUBJECT_ADD_OR_EDIT = TSConstants.MANAGE_CLASSES+SEPARATOR_DOT+ADD_OR_EDIT+"Subject";
	
	public static final String VIEWNAME_ATTENDANCE = TSConstants.MANAGE_CLASSES+SEPARATOR_DOT+"attendance";
	
	public static final String VIEWNAME_TEACHERS = TSConstants.MANAGE_CLASSES+SEPARATOR_DOT+"teachers";
	public static final String VIEWNAME_TEACHER_ADD_OR_EDIT = TSConstants.MANAGE_CLASSES+SEPARATOR_DOT+ADD_OR_EDIT+"Teacher";
	
	
	public static final String VIEWNAME_STUDENT_MARKS_SEARCH = TSConstants.MANAGE_STUDENT_MARKS+SEPARATOR_DOT+SEARCH;
	public static final String VIEWNAME_STUDENT_MARKS_ADD = TSConstants.MANAGE_STUDENT_MARKS+SEPARATOR_DOT+ADD;
	public static final String VIEWNAME_STUDENT_MARKS_SAVE = TSConstants.MANAGE_STUDENT_MARKS+SEPARATOR_DOT+SAVE;
	public static final String VIEWNAME_STUDENT_MARKS_VIEW = TSConstants.MANAGE_STUDENT_MARKS+SEPARATOR_DOT+VIEW;
	public static final String VIEWNAME_STUDENT_MARKS_VIEWALL = TSConstants.MANAGE_STUDENT_MARKS+SEPARATOR_DOT+VIEW_ALL;
	
	public final static String VIEW_ALL_SECTIONS_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_SECTIONS +SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public final static String VIEW_SECTIONS_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_SECTIONS +SEPARATOR_SLASH+TSConstants.ACTION_VIEW+SUFFIX_DOT_HTM;
	public final static String ADD_SECTION_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_SECTIONS+SEPARATOR_SLASH+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	public final static String EDIT_SECTION_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_SECTIONS+SEPARATOR_SLASH+TSConstants.ACTION_EDIT+SUFFIX_DOT_HTM;
	public final static String DELETE_SECTION_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_SECTIONS+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+SUFFIX_DOT_HTM;
	public final static String REORDER_SECTION_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_SECTIONS+SEPARATOR_SLASH+TSConstants.ACTION_REORDER_SECTION+SUFFIX_DOT_HTM;
	
		
	public final static String VIEW_NAME_SECTION ="section";
	
	public final static String FORWARD_VIEW_SECTIONS = FORWARD+SEPARATOR_COLON+TSConstants.ACTION_VIEW_SECTIONS+SUFFIX_DOT_HTM;
	public final static String VIEW_NAME_VIEW_SECTIONS = VIEW_NAME_SECTION+SEPARATOR_DOT+TSConstants.ACTION_VIEW_SECTIONS;
	public final static String VIEW_NAME_ADD_SECTION = VIEW_NAME_SECTION+SEPARATOR_DOT+TSConstants.ACTION_ADD_SECTION;
	public final static String VIEW_NAME_EDIT_SECTION = VIEW_NAME_SECTION+SEPARATOR_DOT+TSConstants.ACTION_EDIT_SECTION;
	
	
	public final static String VIEW_GROUPS_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_GROUPS +SEPARATOR_SLASH+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public final static String ADD_GROUP_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_GROUPS+SEPARATOR_SLASH+TSConstants.ACTION_ADD+SUFFIX_DOT_HTM;
	public final static String EDIT_GROUP_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_GROUPS+SEPARATOR_SLASH+TSConstants.ACTION_EDIT+SUFFIX_DOT_HTM;
	public final static String DELETE_GROUP_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_GROUPS+SEPARATOR_SLASH+TSConstants.ACTION_DELETE+SUFFIX_DOT_HTM;
	
	public final static String VIEW_NAME_GROUP ="group";
	
	
	
	public final static String REDIRECT_VIEW_GROUPS = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_VIEW_GROUPS+SUFFIX_DOT_HTM;
	public final static String VIEW_NAME_VIEW_GROUPS = TSConstants.REPORT_MANAGE_GROUPS+SEPARATOR_DOT+TSConstants.ACTION_VIEWALL;
	public final static String VIEW_NAME_ADD_GROUP = VIEW_NAME_GROUP+SEPARATOR_DOT+TSConstants.ACTION_ADD_GROUP;
	public final static String VIEW_NAME_EDIT_GROUP = VIEW_NAME_GROUP+SEPARATOR_DOT+TSConstants.ACTION_EDIT_GROUP;
	
	public final static String REDIRECT_VIEW_NEWS = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_VIEWALL+SUFFIX_DOT_HTM;
	public final static String VIEW_NAME_VIEW_NEWS = TSConstants.REPORT_MANAGE_NEWS+SEPARATOR_DOT+TSConstants.ACTION_VIEWALL;
	public final static String VIEW_NAME_VIEW_NEWSN = TSConstants.REPORT_MANAGE_NEWS+SEPARATOR_DOT+TSConstants.ACTION_VIEWALL+"N";
	public final static String VIEW_NAME_EDIT_NEWS = TSConstants.REPORT_MANAGE_NEWS+SEPARATOR_DOT+TSConstants.ACTION_EDIT;
	public final static String VIEW_NAME_DELETE_NEWS = TSConstants.REPORT_MANAGE_NEWS+SEPARATOR_DOT+TSConstants.ACTION_DELETE;
	
	
	
	public final static String VIEW_USERS_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_USERS+SEPARATOR_SLASH+VIEW_ALL+SUFFIX_DOT_HTM;
	public final static String ADD_USER_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_USERS+SEPARATOR_SLASH+TSConstants.ACTION_ADD_USER+SUFFIX_DOT_HTM;
	public final static String EDIT_USER_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_USERS+SEPARATOR_SLASH+TSConstants.ACTION_EDIT_USER+SUFFIX_DOT_HTM;
	public final static String DELETE_USER_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_USERS+SEPARATOR_SLASH+TSConstants.ACTION_DELETE_USER+SUFFIX_DOT_HTM;
	public final static String RESET_PASSWORD_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_USERS+SEPARATOR_SLASH+TSConstants.ACTION_RESET_USER_PASSWORD+SUFFIX_DOT_HTM;
	
	public final static String VIEW_NAME_USERS ="user";
	
	public final static String VIEW_NAME_VIEW_USERS = TSConstants.REPORT_MANAGE_USERS+SEPARATOR_DOT+TSConstants.ACTION_VIEWALL;
	public final static String VIEW_NAME_ADD_USER = VIEW_NAME_USERS+SEPARATOR_DOT+TSConstants.ACTION_ADD_USER;
	public final static String VIEW_NAME_EDIT_USER = VIEW_NAME_USERS+SEPARATOR_DOT+TSConstants.ACTION_EDIT_USER;
	public final static String REDIRECT_VIEW_USERS = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_VIEW_USERS+SUFFIX_DOT_HTM;
	
	
	
	public final static String VIEW_ROLES_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_ROLES +SEPARATOR_SLASH+VIEW_ALL+SUFFIX_DOT_HTM;
	public final static String ADD_ROLE_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_ROLES+SEPARATOR_SLASH+TSConstants.ACTION_ADD_ROLE+SUFFIX_DOT_HTM;
	public final static String EDIT_ROLE_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_ROLES+SEPARATOR_SLASH+TSConstants.ACTION_EDIT_ROLE+SUFFIX_DOT_HTM;
	public final static String DELETE_ROLE_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_ROLES+SEPARATOR_SLASH+TSConstants.ACTION_DELETE_ROLE+SUFFIX_DOT_HTM;
	
	public final static String VIEW_NAME_ROLES ="role";
	
	public final static String VIEW_NAME_ADD ="add";
	public final static String VIEW_NAME_EDIT ="edit";
	public final static String VIEW_NAME_DELETE ="delete";
	public final static String VIEW_NAME_VIEW ="view";
	
	public final static String REDIRECT_VIEW_ROLES = REDIRECT+SEPARATOR_COLON+TSConstants.ACTION_VIEW_ROLES+SUFFIX_DOT_HTM;
	public final static String VIEW_NAME_VIEW_ROLES = TSConstants.REPORT_MANAGE_ROLES+SEPARATOR_DOT+VIEW_ALL;
	public final static String VIEW_NAME_ADD_ROLE = TSConstants.REPORT_MANAGE_ROLES+SEPARATOR_DOT+TSConstants.ACTION_ADD_ROLE;
	public final static String VIEW_NAME_EDIT_ROLE = TSConstants.REPORT_MANAGE_ROLES+SEPARATOR_DOT+TSConstants.ACTION_EDIT_ROLE;
	
	public final static String VIEW_PROPERTIES_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_PROPERTIES +SEPARATOR_SLASH+VIEW_ALL+SUFFIX_DOT_HTM;
	public final static String SAVE_PROPERTIES_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_PROPERTIES+SEPARATOR_SLASH+TSConstants.ACTION_SAVE_ALL_PROPERTIES+SUFFIX_DOT_HTM;
	public final static String RELOAD_PROPERTIES_ACTION = TSConstants.ADMIN+SEPARATOR_SLASH+TSConstants.REPORT_MANAGE_PROPERTIES+SEPARATOR_SLASH+TSConstants.ACTION_RELOAD_ALL_PROPERTIES+SUFFIX_DOT_HTM;
	
	
	public final static String VIEW_NAME_PROPERTY ="property";
	
	public final static String FORWARD_VIEW_PROPERTIES = FORWARD+SEPARATOR_COLON+TSConstants.ACTION_VIEW_ALL_PROPERTIES+SUFFIX_DOT_HTM;
	public final static String VIEW_NAME_VIEW_PROPERTIES = VIEW_NAME_PROPERTY+SEPARATOR_DOT+TSConstants.ACTION_VIEW_ALL_PROPERTIES;
	
	
}
